name: Laravel Tests

on:
  push:
    branches:
      - main
      - 2.x
      - v0

  pull_request:
    types: [ready_for_review, synchronize, opened]

  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:8.0
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: wireui_docs
          ports:
              - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install Node Modules
      run: yarn install

    - name: Build Assets
      run: yarn build

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Laravel Pint
      run: ./vendor/bin/pint --test

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test --parallel

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run seed
      run: php artisan db:seed

    - name: Run Migrations Rollback
      run: php artisan migrate:rollback --force
